export const skillIcons = (isDark: boolean) => ({
  astro: "astro",
  sh: isDark ? "bash-dark" : "bash-light",
  bash: isDark ? "bash-dark" : "bash-light",
  c: "c",
  cljs: isDark ? "clojure-dark" : "clojure-light",
  cmake: isDark ? "cmake-dark" : "cmake-light",
  coffee: isDark ? "coffeescript-dark" : "coffeescript-light",
  cpp: "cpp",
  "c++": "cpp",
  cp: "cpp",
  cr: isDark ? "crystal-dark" : "crystal-light",
  crystal: isDark ? "crystal-dark" : "crystal-light",
  cs: "cs",
  csharp: "cs",
  css: "css",
  dart: isDark ? "dart-dark" : "dart-light",
  deno: isDark ? "deno-dark" : "deno-light",
  docker: "docker",
  Dockerfile: "docker",
  dockerfile: "docker",
  dynamodb: isDark ? "dynamodb-dark" : "dynamodb-light",
  fr: "forth",
  fth: "forth",
  forth: "forth",
  f: "fortran",
  fpp: "fortran",
  f77: "fortran",
  for: "fortran",
  gitignore: "git",
  gitattributes: "git",
  git: "git",
  workflow: isDark ? "githubactions-dark" : "githubactions-light",
  github: isDark ? "github-dark" : "github-light",
  gradle: isDark ? "gradle-dark" : "gradle-light",
  graphql: isDark ? "graphql-dark" : "graphql-light",
  graphqls: isDark ? "graphql-dark" : "graphql-light",
  gql: isDark ? "graphql-dark" : "graphql-light",
  haskell: isDark ? "haskell-dark" : "haskell-light",
  hs: isDark ? "haskell-dark" : "haskell-light",
  haxe: isDark ? "haxe-dark" : "haxe-light",
  hx: isDark ? "haxe-dark" : "haxe-light",
  html: "html",
  htm: "html",
  html5: "html",
  java: isDark ? "java-dark" : "java-light",
  jar: isDark ? "java-dark" : "java-light",
  javascript: "javascript",
  js: "javascript",
  cjs: "javascript",
  mjs: "javascript",
  typescript: "typescript",
  ts: "typescript",
  jenkins: isDark ? "jenkins-dark" : "jenkins-light",
  hpi: isDark ? "jenkins-dark" : "jenkins-light",
  julia: isDark ? "julia-dark" : "julia-light",
  jl: isDark ? "julia-dark" : "julia-light",
  kotlin: isDark ? "kotlin-dark" : "kotlin-light",
  kt: isDark ? "kotlin-dark" : "kotlin-light",
  kts: isDark ? "kotlin-dark" : "kotlin-light",
  latex: isDark ? "latex-dark" : "latex-light",
  tex: isDark ? "latex-dark" : "latex-light",
  bib: isDark ? "latex-dark" : "latex-light",
  lua: isDark ? "lua-dark" : "lua-light",
  markdown: isDark ? "markdown-dark" : "markdown-light",
  md: isDark ? "markdown-dark" : "markdown-light",
  matlab: isDark ? "matlab-dark" : "matlab-light",
  m: isDark ? "matlab-dark" : "matlab-light",
  mongodb: "mongodb",
  mysql: isDark ? "mysql-dark" : "mysql-light",
  neovim: isDark ? "neovim-dark" : "neovim-light",
  nvim: isDark ? "neovim-dark" : "neovim-light",
  vim: isDark ? "vim-dark" : "vim-light",
  vi: isDark ? "vim-dark" : "vim-light",
  nextjs: isDark ? "nextjs-dark" : "nextjs-light",
  nim: isDark ? "nim-dark" : "nim-light",
  ocaml: "ocaml",
  ml: "ocaml",
  perl: "perl",
  pl: "perl",
  php: "php",
  postgresql: isDark ? "postgresql-dark" : "postgresql-light",
  postgres: isDark ? "postgresql-dark" : "postgresql-light",
  psql: isDark ? "postgresql-dark" : "postgresql-light",
  powershell: isDark ? "powershell-dark" : "powershell-light",
  ps1: isDark ? "powershell-dark" : "powershell-light",
  ps: isDark ? "powershell-dark" : "powershell-light",
  pub: isDark ? "pub-dark" : "pub-light",
  python: isDark ? "python-dark" : "python-light",
  py: isDark ? "python-dark" : "python-light",
  react: isDark ? "react-dark" : "react-light",
  jsx: isDark ? "react-dark" : "react-light",
  tsx: isDark ? "react-dark" : "react-light",
  regex: isDark ? "regex-dark" : "regex-light",
  rust: "rust",
  rs: "rust",
  ruby: "ruby",
  rb: "ruby",
  sass: "sass",
  scala: isDark ? "scala-dark" : "scala-light",
  solidity: "solidity",
  sol: "solidity",
  sqlite: "sqlite",
  svelte: "svelte",
  swift: "swift",
  v: isDark ? "v-dark" : "v-light",
  vala: "vala",
  vite: isDark ? "vite-dark" : "vite-light",
  vscode: isDark ? "vscode-dark" : "vscode-light",
  webassembly: "webassembly",
  wasm: "webassembly",
  tailwindcss: isDark ? "tailwindcss-dark" : "tailwindcss-light",
  zig: isDark ? "zig-dark" : "zig-light",
  linux: isDark ? "linux-dark" : "linux-light",
});
